import { faker } from '@faker-js/faker';
import { FluxoDeCaixa } from './fluxo-de-caixa.interface';
// import { faker } from '@faker-js/faker/locale/de';

export const FLUXO_DE_CAIXA_MENSAL: FluxoDeCaixa[] = [
  {
    dia: 1,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 2,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 3,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 4,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 5,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 6,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 7,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 8,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 9,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 10,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 11,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 12,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 13,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 14,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 15,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 16,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 17,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 18,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 19,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 10,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 20,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 21,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 22,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 23,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 24,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 25,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 26,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 27,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 28,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 29,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 30,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
  {
    dia: 31,
    receita: faker.finance.amount(),
    despesa: faker.finance.amount(),
    resultadoEsperado: faker.finance.amount(),
    resultadoReal: faker.finance.amount(),
  },
]